name = "user-mgmt-bdcy"
main = "src/index.ts"
compatibility_date = "2024-01-17"


[[services]]
binding = "sessionService"
service = "session-state-bdcy"

[[d1_databases]]
binding = "usersDB"
database_name = "users_bdcy"
database_id = "bc9fa3b0-7a11-4005-8fef-a603215897f2"

[vars]
EMAIL_FROM = ""
EMAIL_FROM_NAME = ""

EMAIL_DKIM_SELECTOR = "mailchannels"
EMAIL_DKIM_DOMAIN = ""
FORGOT_PASSWORD_URL = ""
TOKEN_VALID_MINUTES = 60

[dev]
port = 51512
